### PR TITLE
Partial Hydration in the case of some incorrect data being persisted 

### LINKED ISSUE #2: Failed to hydrate store. Throwing away data from stogare
https://github.com/kuasha420/mst-persistent-store/blob/master/src/index.tsx#L108
It's really wrong practice to delete all the data from the storage. Just dangerous if we have client-only application and store the data that cannot be refetched from the server.
is it possible to apply partly key by key and remove only part of storage that invoke error?

### PR DESCRIPTION
**Pull request by kuasha420**
Tries to fix #2 

Snapshot data can become incorrect when the store structure is updated. 

However, this solution is not ideal and not super robust. 

In the future, we should try to introduce migration functions to handle this case properly. But that requires more thought.

### CODE REVIEW

File: src/utils/is-object.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+const isObject = (value: any): boolean => value !== null && typeof value === 'object';
```
Comment (smamun19) [inline src/utils/is-object.ts]: may be **isPlainObject** is more clear name for this function?

Comment (smamun19) [reply src/utils/is-object.ts]: Also, this function seems problematic, ie **Array**, **Function** , **Date** etc are also treated as object in js

Comment (kuasha420) [reply src/utils/is-object.ts]: Nice catch. I've updated the function name to be `isObjectLike` and added a condition ensuring it's not an array. Since this function only deals with serializable data, this should be sufficient.
